#!/usr/bin/env python3
"""
SEO Agent — Wix Platform Implementation Map
Maps every SEO fix to the exact Wix dashboard path or method.
"""

WIX_SEO_MAP = {
    "meta_tags": {
        "title_tag": {
            "where": "Wix Editor → Click page → Page Settings (gear icon) → SEO (Google) → Page Title",
            "alt_path": "Wix Dashboard → Marketing & SEO → SEO → SEO Settings → select page → Edit",
            "notes": "Wix allows unique title per page. Max ~70 chars displayed. Include primary keyword.",
            "bulk_method": "No native bulk editor. Must be done page by page.",
        },
        "meta_description": {
            "where": "Wix Editor → Click page → Page Settings → SEO (Google) → What's this page about?",
            "notes": "150-160 chars. Include keyword + CTA. Unique per page.",
        },
        "og_tags": {
            "where": "Wix Editor → Page Settings → Social Share → customize title, description, image",
            "notes": "Wix auto-generates OG tags from page settings, but Social Share lets you override.",
        },
        "canonical": {
            "where": "Wix Editor → Page Settings → SEO (Google) → Advanced SEO → scroll to additional tags",
            "notes": "Wix auto-sets self-referencing canonicals. Only change if you have duplicate content issues.",
        },
        "robots_per_page": {
            "where": "Wix Editor → Page Settings → SEO (Google) → Advanced SEO → toggle 'Hide from search results'",
            "notes": "Use to noindex thin pages like thank-you pages or utility pages.",
        },
    },

    "schema_markup": {
        "method_1_structured_data_markup": {
            "where": "Wix Dashboard → Marketing & SEO → SEO Tools → Structured Data Markup",
            "notes": "Wix's built-in tool. Limited to predefined types. Good for LocalBusiness basics.",
        },
        "method_2_custom_code_per_page": {
            "where": "Wix Editor → Page Settings → Advanced SEO → Add structured data markup",
            "notes": "Paste JSON-LD here for page-specific schema (Product, FAQPage, etc). This is the BEST method for custom schema.",
            "steps": [
                "1. Open Wix Editor",
                "2. Click on the page you want to add schema to",
                "3. Click the gear icon (Page Settings)",
                "4. Go to 'SEO (Google)' tab",
                "5. Scroll down to 'Advanced SEO'",
                "6. Click 'Edit' on Structured Data",
                "7. Paste your JSON-LD code",
                "8. Save and publish",
            ],
        },
        "method_3_sitewide_custom_code": {
            "where": "Wix Dashboard → Settings → Custom Code → Add Custom Code → Head",
            "notes": "Use for site-wide schema like Organization. Applies to ALL pages. Set 'Place Code in: Head of every page'",
            "steps": [
                "1. Go to Wix Dashboard",
                "2. Settings → Custom Code",
                "3. Click '+ Add Custom Code'",
                "4. Paste the <script type='application/ld+json'>...</script> block",
                "5. Name it (e.g., 'Organization Schema')",
                "6. Place code in: Head",
                "7. Add to: All pages",
                "8. Save",
            ],
        },
        "method_4_wix_velo": {
            "where": "Wix Editor → Dev Mode → Enable Velo → masterPage.js or page code",
            "notes": "Advanced: Use Wix Velo to dynamically inject schema based on page content. Best for product/blog pages at scale.",
        },
    },

    "robots_txt": {
        "where": "Wix Dashboard → Marketing & SEO → SEO Tools → robots.txt Editor",
        "notes": "Wix auto-generates robots.txt. You can ADD custom rules but CANNOT fully replace it. Wix's auto-generated directives remain.",
        "limitations": [
            "Cannot remove Wix's default directives",
            "Can add custom User-agent and Disallow/Allow rules",
            "Sitemap directive is auto-added by Wix",
            "AI bot rules CAN be added here",
        ],
        "recommended_additions": """
# Allow AI crawlers for AIEO/GEO visibility
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /
""",
    },

    "sitemap": {
        "where": "Auto-generated by Wix at yourdomain.com/sitemap.xml",
        "notes": "Wix auto-generates and auto-submits sitemap. You CANNOT manually edit it. Pages are included/excluded based on their SEO visibility settings.",
        "control": "To exclude a page: Page Settings → SEO → Advanced SEO → 'Hide this page from search results'",
        "submit": "Wix auto-submits to Google. Verify in Google Search Console → Sitemaps.",
    },

    "url_structure": {
        "where": "Wix Editor → Page Settings → SEO (Google) → URL slug",
        "notes": "You can customize the URL slug per page. Keep it short, keyword-rich, lowercase, hyphenated.",
        "limitations": [
            "Wix adds base paths for certain page types (e.g., /blog/ for blog posts)",
            "Dynamic pages (Wix CMS) have URL patterns you configure in the dataset settings",
            "Cannot remove .html extension on some older Wix sites (newer sites don't have this)",
        ],
        "best_practices": [
            "Use: /event-pod-rental (not /event_pod_rental or /EventPodRental)",
            "Keep under 60 characters",
            "Include primary keyword",
            "No stop words unless needed for readability",
        ],
    },

    "redirects": {
        "where": "Wix Dashboard → Marketing & SEO → SEO Tools → URL Redirect Manager",
        "notes": "Add 301 redirects for changed URLs. Supports individual and group redirects.",
        "steps": [
            "1. Dashboard → Marketing & SEO → SEO Tools",
            "2. Click 'URL Redirect Manager'",
            "3. Click '+ New Redirect'",
            "4. Enter old URL and new URL",
            "5. Select redirect type (301 permanent recommended)",
            "6. Save",
        ],
    },

    "images": {
        "alt_text": {
            "where": "Wix Editor → Click image → Image Settings (gear icon) → What's in the image? (Alt text)",
            "notes": "Add descriptive alt text to every image. Wix also allows tooltip text separately.",
        },
        "optimization": {
            "notes": [
                "Wix auto-compresses images on upload",
                "Wix serves images in WebP format automatically to supported browsers",
                "Wix handles responsive images via their image CDN",
                "Lazy loading is automatic for below-fold images on newer Wix sites",
                "Upload high-quality source images — Wix handles the optimization",
                "Use Wix's built-in image editor to crop/resize BEFORE publishing",
            ],
        },
    },

    "headings": {
        "where": "Wix Editor → Select text → Change text style from the text editor toolbar",
        "notes": [
            "Wix maps text styles to HTML headings: Heading 1 = H1, Heading 2 = H2, etc.",
            "Ensure every page has exactly ONE H1 (usually the main page title)",
            "Use H2s for major sections, H3s for subsections",
            "Don't use heading styles just for visual size — use them for semantic structure",
            "Wix's default themes sometimes use H1 for the site title in the header on EVERY page — check this",
        ],
    },

    "custom_code_injection": {
        "sitewide_head": {
            "where": "Wix Dashboard → Settings → Custom Code → Add to Head of every page",
            "use_for": "Organization schema, global meta tags, Google Analytics, Google Tag Manager, verification codes",
        },
        "sitewide_body_start": {
            "where": "Wix Dashboard → Settings → Custom Code → Add to Body start of every page",
            "use_for": "GTM noscript tag, chat widgets",
        },
        "per_page_head": {
            "where": "Wix Editor → Page Settings → Advanced SEO → Custom Code / Structured Data",
            "use_for": "Page-specific schema, page-specific meta tags",
        },
    },

    "core_web_vitals": {
        "notes": [
            "Wix handles most server-side performance (hosting, CDN, caching)",
            "You have LIMITED control over CWV on Wix",
            "What you CAN do:",
            "  - Reduce number of apps/plugins (each adds JS bloat)",
            "  - Optimize images (upload correct size, use Wix's built-in tools)",
            "  - Minimize custom code in head (blocks rendering)",
            "  - Use Wix's built-in elements over custom HTML embeds when possible",
            "  - Remove unused page elements and hidden sections",
            "  - Limit animations and complex interactions",
            "  - Use Wix's Lightbox sparingly (affects CLS)",
            "What you CANNOT control:",
            "  - Server response time (Wix infrastructure)",
            "  - Wix's own JavaScript bundle size",
            "  - CDN configuration",
            "  - HTTP/2 or HTTP/3 settings",
        ],
    },

    "google_search_console": {
        "where": "Wix Dashboard → Marketing & SEO → SEO Tools → Go to Google Search Console",
        "notes": "Wix can auto-verify your site with GSC. If not connected, add the verification meta tag via Custom Code.",
    },

    "google_business_profile": {
        "where": "business.google.com (external — not in Wix)",
        "notes": "Claim/create your GBP separately. Ensure NAP matches your Wix site exactly.",
    },

    "llms_txt": {
        "notes": [
            "Wix does NOT support custom static files at arbitrary URLs",
            "WORKAROUND OPTIONS:",
            "  1. Create a new page at /llms-txt and add the content as text (won't be .txt format but still crawlable)",
            "  2. Use Wix Velo to create a router that serves /llms.txt as plain text",
            "  3. Use a Wix HTTP function (backend) to serve the file — requires Velo/coding",
            "  4. Host llms.txt on a subdomain or separate service and CNAME it",
        ],
    },

    "blog": {
        "where": "Wix Dashboard → Blog → Create New Post",
        "seo_settings": "In post editor → SEO Settings (left panel) → Edit title, description, URL slug",
        "notes": [
            "Wix Blog auto-generates /blog/ URL prefix",
            "Each post gets its own SEO settings",
            "Tags and categories help with internal linking",
            "Featured image becomes the OG image",
            "Wix Blog supports author bio — use it for E-E-A-T",
        ],
    },
}


def print_wix_guide():
    """Print the full Wix SEO implementation guide."""
    print("\n" + "=" * 70)
    print("  WIX SEO IMPLEMENTATION GUIDE — ZenSpace Events")
    print("=" * 70)

    for category, details in WIX_SEO_MAP.items():
        print(f"\n{'─'*70}")
        print(f"  📌 {category.upper().replace('_', ' ')}")
        print(f"{'─'*70}")

        if isinstance(details, dict):
            for key, val in details.items():
                if isinstance(val, dict):
                    print(f"\n  ▸ {key.replace('_', ' ').title()}")
                    for k, v in val.items():
                        if isinstance(v, list):
                            print(f"    {k}:")
                            for item in v:
                                print(f"      • {item}")
                        else:
                            print(f"    {k}: {v}")
                elif isinstance(val, list):
                    print(f"\n  {key}:")
                    for item in val:
                        print(f"    • {item}")
                elif isinstance(val, str):
                    print(f"  {key}: {val}")
        print()

    print("=" * 70)
    print("  KEY WIX LIMITATIONS TO KNOW:")
    print("=" * 70)
    print("  1. Cannot fully replace robots.txt — can only ADD rules")
    print("  2. Cannot manually edit sitemap.xml — it's auto-generated")
    print("  3. Limited server-side performance control (CWV depends on Wix)")
    print("  4. Cannot create arbitrary static files (e.g., llms.txt) without Velo")
    print("  5. JavaScript-heavy rendering — ensure content is in static HTML, not just JS")
    print("  6. Custom code in <head> can hurt CWV if not careful")
    print("  7. Each page's schema must be added individually (no bulk tool)")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    print_wix_guide()
